
services:
  backend:
    container_name: 'backend'
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8090:8090"
    
  db:
    container_name: 'db'
    image: "postgres:17"
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${DB_PORT}:${DB_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data
    
  frontend:
    container_name: "frontend"
    build: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "5173:5173"
    
volumes:
  pg_data: